### ISSUE TITLE
Auto Theme Not Working in the Map View

### ISSUE THREAD

**Issue by VSuryaPrashanth** [esm7/obsidian-map-view#274] opened 2024-09-17 18:43 UTC
# System Info
OS: macOS Sequoia & iOS 18.1
Obsidian Version: v1.6.7
Obsidian Theme: AnuPpuccin
Map View Version: 5.0.3

# What is the issue?
Changing System wide Dark/Light Mode does not affect the Map View's Color Palette.

# How to replicate the issue?
Step 1: Set `Settings -> Appearance -> Base Color Scheme -> "Adapt to system"`
Step 2: Set `View -> Auto`
Step 3: Changing System to `Dark Mode` or `Light Mode` affects the Obsidian theme but not Map View

# What is the expected result?
Changing the System theme should change the Map View's theme

**Comment by t3mujin** [comment] 2024-10-15 18:09
This likely is a duplicate of #136

**Closed** 2024-10-20 04:39 UTC
