### ISSUE TITLE
$CURSOR$ added to each new location note

### ISSUE THREAD

**Issue by kristofferR** [esm7/obsidian-map-view#21] opened 2021-08-08 04:31 UTC
When I right-click the map and create a "New note here", the text $CURSOR$ is always added to my note, leading to an italic _CURSOR_ text in preview mode.

**Comment by aidanlw505** [comment] 2022-12-05 14:32
I have reproduced this too. I've found that the issues appears to be because I have "Default view for new tabs" set to "Reading view." I believe the plugin is adding the text upon creation and the editor doesn't get a chance to delete it.

**Comment by championswimmer** [comment] 2022-12-26 06:06
I am facing the same problem

**Comment by esm7** [comment] 2023-01-12 08:53
Fixed in 3.0.0. After a very long time of being unable to recreate this, the comment by @aidanlw505 pointing out this happens due to "reading view" finally made me understand how this is happening for some users!

**Closed by esm7** 2023-01-12 08:53 UTC
Labels: p0
