### ISSUE TITLE
Can't add place that has a "/" in the name

### ISSUE THREAD

**Issue by antonbrall** [esm7/obsidian-map-view#221] opened 2024-01-18 16:25 UTC
There is a place that is called "Vugi / Olympus Träningscenter (Slottsallén 23, 352 52 Växjö, Sweden)" on the google Places API.
Because of the "/" it can not be used as a filename.
This is the error message:

`Uncaught (in promise) Error: Cannot create file named vault/places/Vugi / Olympus Träningscenter (Slottsallén 23, 352 52 Växjö, Sweden): Error: ENOENT: no such file or directory, open '/mypath/vaultname/places/Vugi / Olympus Träningscenter (Slottsallén 23, 352 52 Växjö, Sweden).md'`

**Comment by ParkerRobb** [comment] 2024-01-18 18:58
Probably a duplicate of #207

**Comment by antonbrall** [comment] 2024-01-18 19:46
@ParkerRobb yes it is, didn't see that one, thanks.

**Comment by antonbrall** [comment] 2024-01-18 19:47
Duplicate of #207

**Closed** 2024-01-18 19:47 UTC
