### ISSUE TITLE
Bug: Not possible to add locations via smartphone (Android)

### ISSUE THREAD

**Issue by timtester-boop** [esm7/obsidian-map-view#96] opened 2022-05-31 16:35 UTC
When using the map view plugin on a smartphone, I'm not able to add new locations (notes) via the map itself. When I press and hold a point on the map, the context menu appears where I can chose to generate a new note (inline or front matter). But no matter which one I click, nothing happens. No new note is generated, not even in the background. The only way to add locations to the map on my smartphone is to chose "copy geolocation (as front matter)" from the context menu, manually add a new note to my vault and paste the geolocation into the note.

Tested on two different Android phones with the latest version of the plugin.

**Comment by esm7** [comment] 2022-06-01 11:02
Turns out it happens for me too. Will look for the cause.

**Comment by esm7** [comment] 2022-06-02 19:07
Fixed in 2.0.5.

**Closed by esm7** 2022-06-02 19:07 UTC

**Comment by timtester-boop** [comment] 2022-06-06 13:27
It works - thank you! 😊
